
responses= { "hello" : "Hi there!",
            "i lost my debit card" : "I've ordered a new one for you,
            "i can't get into my account" : "You can reset your password under the Forgot Password section on the login page",
            "my card has been stolen" : "I have cancelled that card and ordered a new one for you",
            "how do i check the funds in my account" : "You may either come into one of our locations or download our banking app",
            "can i speak to a sales representitive" : "Sure let me forward you to a representitive now",
            "how do i transfer funds from my account" : "You will need to use our app for a transfer",
            "how do i open a savings account" : "you will need to talk to an associate. I'll forward you now",
            "how do i open a checking account" : "you will need to talk to an associate. I'll forward you now",
            "is there any suspicios activity on my account" : "you can either check the My Transactions section on the app or I can forward you to an associate",
            "can i talk to an associate" : "I'll forward you now",
            "what is my account balance" : "You can check your available balance by checking the My Balance secton of the app or you ca visit one of our locations",
            "can i put my account on hold?" : "Certaintly! I'll take care of it for you",
            "i would like to setup an account for a child" : "You will need to bring your child to one of our locations in order to set that up",
            "what is te annual fee on my credit card" : "The annual fee for all of our cards is $450",
